"""
tests/unit/test_config_serialization.py
========================================
Unit coverage for :class:`ContinuumConfig`'s serialisation + convenience
surface: ``yaml_schema`` (annotated template generation), ``to_yaml``
(effective-config dump), ``load``, and the scoring helpers
(``as_tuple`` / ``apply`` / ``recency_score`` / ``scoring_weights_tuple``).

Pure-logic, no I/O, no network.
"""

from __future__ import annotations

import math

import pytest
import yaml

from continuum.core.config import ContinuumConfig

pytestmark = pytest.mark.unit


def _weights():  # type: ignore[no-untyped-def]
    # ScoringWeights lives on the scoring config; reach it via a default instance.
    return ContinuumConfig().scoring.weights


# ── yaml_schema (annotated template) ─────────────────────────────────────────


def test_yaml_schema_is_valid_yaml_and_annotated() -> None:
    text = ContinuumConfig.yaml_schema()
    assert isinstance(text, str)
    # Carries the generated-by header comment and at least one annotation.
    assert "generated by ContinuumConfig.yaml_schema()" in text
    assert "#" in text
    # The non-comment body must parse as YAML.
    body = "\n".join(ln for ln in text.splitlines() if not ln.lstrip().startswith("#"))
    parsed = yaml.safe_load(body)
    assert isinstance(parsed, dict)
    # Recurses into nested sections (scoring is a sub-model).
    assert "scoring" in parsed


def test_yaml_schema_round_trips_into_a_loadable_config() -> None:
    # The template's values are the defaults, so the parsed body should be
    # accepted by the model (sanity that we didn't emit malformed values).
    text = ContinuumConfig.yaml_schema()
    body = "\n".join(ln for ln in text.splitlines() if not ln.lstrip().startswith("#"))
    parsed = yaml.safe_load(body)
    assert isinstance(parsed.get("scoring"), dict)


# ── to_yaml (effective config dump) ──────────────────────────────────────────


def test_to_yaml_dumps_effective_config() -> None:
    cfg = ContinuumConfig()
    out = cfg.to_yaml()
    assert isinstance(out, str)
    round_tripped = yaml.safe_load(out)
    assert isinstance(round_tripped, dict)
    assert "scoring" in round_tripped


# ── load / convenience helpers ───────────────────────────────────────────────


def test_load_applies_overrides() -> None:
    cfg = ContinuumConfig.load(environment="production")
    assert cfg.environment == "production"
    assert cfg.is_production() is True


def test_is_production_false_by_default() -> None:
    assert ContinuumConfig().is_production() is False


def test_scoring_weights_tuple_matches_weights() -> None:
    cfg = ContinuumConfig()
    t = cfg.scoring_weights_tuple()
    assert isinstance(t, tuple)
    assert len(t) == 4
    assert math.isclose(sum(t), 1.0, abs_tol=1e-6)


# ── scoring math (ScoringWeights / ScoringConfig) ────────────────────────────


def test_weights_as_tuple_and_apply() -> None:
    w = _weights()
    rel, imp, rec, conf = w.as_tuple()
    assert math.isclose(rel + imp + rec + conf, 1.0, abs_tol=1e-6)
    # apply is the dot product, clamped to [0, 1]
    score = w.apply(relevance=1.0, importance=1.0, recency=1.0, confidence=1.0)
    assert math.isclose(score, 1.0, abs_tol=1e-6)
    zero = w.apply(relevance=0.0, importance=0.0, recency=0.0, confidence=0.0)
    assert zero == 0.0


def test_apply_clamps_to_unit_interval() -> None:
    w = _weights()
    # Out-of-range inputs still clamp into [0, 1].
    assert w.apply(relevance=10.0, importance=10.0, recency=10.0, confidence=10.0) == 1.0


def test_recency_score_halves_at_tau() -> None:
    scoring = ContinuumConfig().scoring
    tau = scoring.tau_hours
    assert math.isclose(scoring.recency_score(0.0), 1.0, abs_tol=1e-9)
    assert math.isclose(scoring.recency_score(tau), 0.5, abs_tol=1e-9)
    assert math.isclose(scoring.recency_score(2 * tau), 0.25, abs_tol=1e-9)
